/////LISTS

####Get
GET http://localhost:3000/lists/43
Accept: application/json


####Post
POST http://localhost:3000/lists
Accept: application/json
Content-Type: application/json

{
  "name": "Must have"
}

####Patch
PATCH http://localhost:3000/lists/7
Accept: application/json
Content-Type: application/json

{
  "name": "PATCD"
}

####Delete
DELETE http://localhost:3000/lists/4

////TASKS

####Get
GET http://localhost:3000/tasks/75
Accept: application/json

####Post
POST http://localhost:3000/tasks
Accept: application/json
Content-Type: application/json

{
  "name": "new task3",
  "dueDate": "2022-08-21",
  "done": false,
  "description": "description of new task3",
  "listId": 22
}

####Patch
PATCH http://localhost:3000/tasks/7
Accept: application/json
Content-Type: application/json

{
  "name": "PATCD"
}

####Delete
DELETE http://localhost:3000/tasks/4

####Put task
PUT http://localhost:3000/tasks/7
Accept: application/json
Content-Type: application/json

{
  "description": "New description",
  "listId": 9
}

####Dashboard
GET http://localhost:3000/today